import carImage from '../../assets/images/car.png'
import carImageWhite from '../../assets/images/car-2.png'
import civic2020Image from '../../assets/images/20200111-HONDA-CIVIC-2020-AA01.png'
import crv2020Image from '../../assets/images/20200211-HONDA-CR-V-2020-COLOMBIA-ADELANTO-01.png'
import fitEhevImage from '../../assets/images/RT_V_d93c78ab22294e5587e3b21df249a41f.png'
import sedanConceptImage from '../../assets/images/maxresdefault.png'

// Especificaciones conceptuales de ejemplo; no son datos oficiales de Honda.
export const models = [
  {
    name: 'Civic',
    category: 'SEDÁN',
    image: civic2020Image,
    imageAlt: 'Honda Civic 2020 Type R azul',
    description: 'Diseño deportivo, tecnología avanzada y una experiencia de conducción excepcional.',
    detailDescription: 'Un compacto de carácter deportivo que combina respuesta ágil, control preciso y comodidad para el uso diario.',
    engineDesignation: '2.0 Turbo Sport',
    motorType: '4 cilindros, turbo a gasolina',
    power: 'Aproximadamente 280 hp',
    torque: 'Aproximadamente 295 lb-ft',
    fuelConsumption: 'Aproximadamente 11–13 km/L combinado',
    transmission: 'Manual de 6 velocidades',
    technology: 'Diferencial de deslizamiento limitado para mejorar la tracción.',
  },
  {
    name: 'Sedán Touring Concept',
    category: 'SEDÁN',
    image: sedanConceptImage,
    imageAlt: 'Sedán Honda gris oscuro, modelo conceptual',
    description: 'Elegancia, confort y potencia para disfrutar cada trayecto con máxima comodidad.',
    detailDescription: 'Un sedán conceptual de enfoque refinado, pensado para ofrecer viajes cómodos, respuesta progresiva y eficiencia equilibrada.',
    engineDesignation: '1.5 Turbo Touring Concept',
    motorType: '4 cilindros, turbo a gasolina',
    power: 'Aproximadamente 190 hp',
    torque: 'Aproximadamente 192 lb-ft',
    fuelConsumption: 'Aproximadamente 13–16 km/L combinado',
    transmission: 'Automática CVT',
    technology: 'Modos de conducción para adaptar la respuesta del vehículo.',
  },
  {
    name: 'CR-V',
    category: 'SUV',
    image: crv2020Image,
    imageAlt: 'Honda CR-V 2020 para Colombia',
    description: 'Espacio, seguridad y tecnología para acompañarte en cada aventura.',
    detailDescription: 'Una SUV versátil con cabina amplia y una configuración híbrida conceptual para combinar desempeño y eficiencia.',
    engineDesignation: '2.0 e:HEV',
    motorType: 'Híbrido: 4 cilindros y motores eléctricos',
    power: 'Aproximadamente 204 hp combinados',
    torque: 'Aproximadamente 247 lb-ft combinados',
    fuelConsumption: 'Aproximadamente 16–19 km/L combinado',
    transmission: 'e-CVT',
    technology: 'Gestión híbrida que alterna entre propulsión eléctrica y de combustión.',
  },
  {
    name: 'HR-V',
    category: 'SUV COMPACTA',
    image: carImageWhite,
    description: 'Un formato urbano con espacio inteligente y estilo contemporáneo.',
    detailDescription: 'Una SUV compacta diseñada para moverse con facilidad en la ciudad, con una posición de manejo elevada y un interior flexible.',
    engineDesignation: '2.0 i-VTEC',
    motorType: '4 cilindros atmosférico a gasolina',
    power: 'Aproximadamente 158 hp',
    torque: 'Aproximadamente 138 lb-ft',
    fuelConsumption: 'Aproximadamente 13–16 km/L combinado',
    transmission: 'Automática CVT',
    technology: 'Asistencia de estabilidad y modos de conducción seleccionables.',
  },
  {
    name: 'Pilot',
    category: 'SUV',
    image: carImage,
    description: 'Una SUV amplia pensada para compartir viajes y nuevos destinos.',
    detailDescription: 'Una SUV familiar de tres filas que prioriza la amplitud, la comodidad en carretera y una entrega de potencia suave.',
    engineDesignation: '3.5 V6 Adventure',
    motorType: 'V6 atmosférico a gasolina',
    power: 'Aproximadamente 285 hp',
    torque: 'Aproximadamente 262 lb-ft',
    fuelConsumption: 'Aproximadamente 9–11 km/L combinado',
    transmission: 'Automática de 10 velocidades',
    technology: 'Control de tracción para mejorar el avance en superficies variables.',
  },
  {
    name: 'City Hatchback',
    category: 'HATCHBACK',
    image: fitEhevImage,
    imageAlt: 'Hatchback Honda compacto azul',
    description: 'Agilidad para la ciudad con una propuesta versátil y funcional.',
    detailDescription: 'Un hatchback compacto pensado para la ciudad, con espacio adaptable y una conducción práctica para el día a día.',
    engineDesignation: '1.5 i-VTEC City (datos de ejemplo)',
    motorType: '4 cilindros atmosférico a gasolina',
    power: 'Aproximadamente 121 hp (dato de ejemplo)',
    torque: 'Aproximadamente 107 lb-ft (dato de ejemplo)',
    fuelConsumption: 'Aproximadamente 15–18 km/L combinado (dato de ejemplo)',
    transmission: 'Automática CVT (dato de ejemplo)',
    technology: 'Asientos traseros abatibles para ampliar el espacio de carga.',
  },
]
